### ISSUE TITLE
UIButton

### ISSUE THREAD

**Issue by elocogy** [elocogy/iOS-Swift-UI#2]
StoryBoard上の任意の位置に、UILabelとUIButtonを配置し、ボタンを押すごとにUILabelのテキストカラーをランダムに変更してください。

**Comment by elocogy** [comment]
課題着手の宣言やコミット時のissueとのリンクを忘れてたので次から実践する。

**Comment by OnTheWaves** [comment]
IBActionのデータ型は、UIButtonのように明示的にしたほうが、扱いやすいし、無駄なキャストが減りますよ。

```
//現状
@IBAction func pushBtn(sender: AnyObject) {
}

//改善案
@IBAction func pushBtn(sender: UIButton) {
}
```

**Comment by elocogy** [comment]
串田さん
ご指摘ありがとうございます。
AnyObjectをUIButtonに変更しました。
また、enumも使ってみたのですが、使い方が間違ってたりもっといい書き方がありましたら
ご教授お願い致します。

**Comment by OnTheWaves** [comment]
@elocogy 問題ないと思います。 Masterにマージしちゃってください。

**Comment by elocogy** [comment]
@OnTheWaves ご確認いただきありがとうございます。マージしました！！！
